#!/usr/bin/env ruby
PAGETITLE = "Second someone for ASF Member" # Wvisible:meeting
$LOAD_PATH.unshift '/srv/whimsy/lib'
require 'time'
require 'wunderbar'
require 'wunderbar/bootstrap'
require 'whimsy/asf'
require 'whimsy/asf/forms'
require 'whimsy/asf/member-files' # See for nomination file parsing
require 'whimsy/asf/wunderbar_updates'
require 'whimsy/asf/meeting-util'
require_relative '../../tools/parsemail'
require 'whimsy/asf/time-utils'
require 'mail'

MAILING_LIST = 'members@apache.org'
MAIL_ROOT = '/srv/mail' # TODO: this should be config item

# Try to find matching message id for the original nomination email
def find_mesgid(subject)
  ParseMail.parse_main(['members']) # ensure we are up to date
  today = Date.today
  msgids = [] # potential matches
  [today.strftime("%Y%m"), (today<<1).strftime("%Y%m")].each do |yyyymm|
    curfile = File.join(MAIL_ROOT, "members", "#{yyyymm}.yaml")
    yaml = YamlFile.read(curfile)
    yaml.each do |key, value|
      if subject == value[:Subject]
        msgid = value[:MessageId]
        if msgid.include? '@whimsy' # currently @whimsy1-ec2-va.mail
          return msgid # This must be it
        else
          msgids << msgid # could be the one
        end
      end
    end
  end
  return msgids.first if msgids.size == 1
  # else did not find unique match
  nil
end

def emit_form(title, prev_data, nominees)
  _whimsy_panel(title, style: 'panel-success') do
    _form.form_horizontal method: 'post' do
      field = 'nominee'
      _whimsy_forms_select(label: 'Nominee', name: field,
        multiple: false,
        options: nominees,
        selectExtra: {onChange: 'show_seconds()'},
        helptext: 'Select the nominee you are seconding for ASF Membership'
      )
      _whimsy_forms_input(label: 'Existing Seconds', name: 'seconds', readonly: true, value: ''
      )
      _whimsy_forms_input(label: 'Seconded by', name: 'secby', readonly: true, value: $USER
      )
      field = 'statement'
      _whimsy_forms_input(label: 'Second Statement', name: field, rows: 10,
        value: prev_data[field], helptext: 'Explain why you believe this person would make a good ASF Member, and what projects/communities they work on at the ASF'
      )
      _whimsy_forms_submitwrap(
        noicon: true, label: 'submit', name: 'submit', value: 'submit', helptext: 'Checkin this second and send email to members@'
      )
    end
  end
end

# Validation as needed within the script
# Returns: 'OK' or a text message describing the problem
def validate_form(formdata: {})
  nominee = formdata['nominee']
  return "You MUST provide a second statement for Candidate #{nominee}; blank was provided!" if formdata['statement'].empty?
  return 'OK'
end

# Handle submission (checkout user's apacheid.json, write form data, checkin file)
# @return true if we think it succeeded; false in all other cases
def process_form(formdata: {}, wunderbar: {})
  _h3 "Transcript of update to nomination file #{ASF::MemberFiles::NOMINATED_MEMBERS}"
  entry = {
    nominee: formdata['nominee'], # to find the entry
    secby: formdata['secby'], # add to seconds
    statement: formdata['statement'] # the data
  }
  environ = Struct.new(:user, :password).new($USER, $PASSWORD)
  ASF::MemberFiles.commit_member_second(environ, wunderbar, entry, "+= second for #{formdata['nominee'].downcase}")
  return true
end

# Send email to members@ with this second's data
# Reports status to user in a _div
def send_confirmation_mail(formdata: {})
  nominee = formdata['nominee'].strip # e.g. uid <Public Name>
  uid, public_name = nominee.split(' ', 2) # single space means any whitespace
  uid.downcase! # just in case
  public_name.delete_prefix!('<').delete_suffix!('>') # trim the markers
  secby = formdata.fetch('secby', nil)
  mail_body = <<-MAILBODY
Added second by #{secby} for #{nominee} as a New Member:

#{formdata['statement']}

--
- #{ASF::Person[secby].public_name}
  Email generated by Whimsy (#{File.basename(__FILE__)})

MAILBODY
  # See check_membernoms.cgi which parses this in list archives
  if uid == 'n/a'
    mailsubject_original = "[MEMBER NOMINATION] #{public_name}"
  else
    mailsubject_original = "[MEMBER NOMINATION] #{public_name} (#{uid})"
  end
  mailsubject = "Re: #{mailsubject_original}"
  msgid = find_mesgid(mailsubject_original)
  ASF::Mail.configure
  mail = Mail.new do
    to MAILING_LIST
    bcc 'notifications@whimsical.apache.org'
    from "#{ASF::Person[secby].public_name} <#{secby}@apache.org>"
    subject mailsubject
    in_reply_to msgid if msgid
    text_part do
      body mail_body
    end
  end
  begin
    mail.deliver!
  rescue StandardError => e
    _div.alert.alert_danger role: 'alert' do
      _p.strong "ERROR: email was NOT sent due to: #{e.message} #{e.backtrace[0]}"
      _p do
        _ "To: #{MAILING_LIST}"
        _br
        _ "Subject: #{mailsubject}"
        _br
        _ "#{mail_body}"
      end
    end
    return
  end
  _div.alert.alert_success role: 'alert' do
    _p "The following email was sent:"
    _p do
      _ "To: #{MAILING_LIST}"
      _br
      _ "Subject: #{mailsubject}"
      _br
      _ "#{mail_body}"
    end
  end
  return
end

# Produce HTML
_html do
  nominations = ASF::MemberFiles.nominated_members
  _body? do
    # Countdown until nominations for current meeting close
    latest_meeting_dir = ASF::MeetingUtil.latest_meeting_dir
    timelines = ASF::MeetingUtil.get_timeline(latest_meeting_dir)
    t_now = Time.now.to_i
    t_end = Time.parse(timelines['vote_create_date']).to_i
    secclosed = t_now > t_end
    _whimsy_body(
      title: PAGETITLE,
      subtitle: 'About This Script',
      related: {
        'meeting.cgi' => 'Member Meeting FAQ and info',
        '/roster/committer/' => 'Lookup any committer availID',
        'memberless-pmcs.cgi' => 'PMCs with no/few ASF Members',
        'watch.cgi' => 'Watch list for potential Member candidates',
        'check_membernoms.cgi' => 'Cross-check existing Member nominations',
        ASF::SVN.svnpath!('Meetings') => 'Official Meeting Agenda Directory'
      },
      helpblock: -> {
        _b "For: #{timelines['meeting_type']} Meeting on: #{timelines['meeting_iso']}"
        _p do
          _br
          _ %Q{
            Use this form to add a second to an existing nomination for ASF Membership.
            It automatically adds a properly formatted entry to the #{ASF::MemberFiles::NOMINATED_MEMBERS} file,
            and will then
          }
          _strong "send an email to the #{MAILING_LIST} list"
          _ ' from you with the details of the second.'
        end
      }
    ) do

      if secclosed
        _h1 'Nominations are now closed!'
        _p 'Sorry, no further seconds will be accepted for ballots at this meeting.'
      else
        _h3 "Nominations close in #{ASFTime.secs2text(t_end - t_now)} at #{Time.at(t_end).utc} for Meeting: #{timelines['meeting_iso']}"
      end

      _div id: 'second-form' do
        if _.post?
          unless secclosed
            submission = _whimsy_params2formdata(params)
            valid = validate_form(formdata: submission)
          end
          if secclosed
            _div.alert.alert_warning role: 'alert' do
              _p "Nominations have closed"
            end
          elsif valid == 'OK'
            if process_form(formdata: submission, wunderbar: _)
              _div.alert.alert_success role: 'alert' do
                _p "Your second was submitted to svn; now sending email to #{MAILING_LIST}."
              end
              mailval = send_confirmation_mail(formdata: submission)
            else
              _div.alert.alert_danger role: 'alert' do
                _p do
                  _span.strong "ERROR: Form data invalid in process_form(), update was NOT submitted!"
                  _br
                  _ "#{submission}"
                end
              end
            end
          else
            _div.alert.alert_danger role: 'alert' do
              _p do
                _span.strong "ERROR: Form data invalid in validate_form(), update was NOT submitted!"
                _br
                _p valid
              end
            end
          end
        else # if _.post?
          if secclosed
            _p do
              _ 'Sorry, no further seconds will be accepted for ballots at this meeting.'
              # _br
              # _a 'See existing nominations.', href: '/members/check_membernoms.cgi'
            end
          else
            emit_form('Enter your New Member second', {}, nominations.keys)
          end
        end
      end
    end
    # '_' does not work in _script blocks when wunderbar/bootstrap (i.e. wunderbar/jquery is included)
    # so create the JS code as a string
    jscode = []
    jscode << 'let map = new Map();'
    nominations.each do |k,v|
      jscode << "map.set(#{k.inspect}, #{v.inspect});"
    end
    jscode.push <<~'EOJSCODE'
    function show_seconds() {
      let nominee = document.getElementById('nominee').value;
      document.getElementById('seconds').value = map.get(nominee);
    }
    EOJSCODE
    _script jscode.join("\n")
  end
end
