source 'https://rubygems.org'

gem 'rake'
gem 'wunderbar', '>= 1.0.0'
gem 'ruby2js', '>= 2.0.0'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs', ('<2.5.1' if RUBY_VERSION =~ /^1/)
gem 'whimsy-asf', '>= 0.0.14'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
end

group :demo do
  gem 'puma'
  gem 'listen', ('~> 3.0.7' if RUBY_VERSION =~ /^2\.[01]/)
end
