version: '3'
services:
  web: # must agree with Rakefile
    image: whimsy-web
    build: .
    ports:
      - "1999:80"
    environment:
      - "HOST_HOME=$HOME"
    volumes:
      - ..:/srv
    # Needed to run puppeteer
    cap_add:
      - SYS_ADMIN
