version: '3'
services:
  web: # must agree with Rakefile
    image: whimsy-web
    build: .
    ports: 
      - "1999:80"
    environment:
      - "HOST_HOME=$HOME"
    volumes:
      - ..:/srv
# https://github.com/apache/whimsy/issues/119
# These don't appear to be needed
#      - $HOME/.subversion:/$HOME/.subversion
#      - $HOME/.ssh:/$HOME/.ssh
