source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'rake'
gem 'wunderbar', '~> 1.1.1'
gem 'ruby2js', '>= 2.0.17'
gem 'sinatra', '~> 2.0'
gem 'nokogumbo'
gem 'execjs', ('<2.5.1' if RUBY_VERSION =~ /^1/)
gem 'listen', ('~> 3.0.7' if RUBY_VERSION =~ /^2\.[01]/)
gem 'activesupport'
gem 'mail'

gem 'websocket-eventmachine-server'
gem 'websocket-client-simple'
gem 'concurrent-ruby'

gem 'mime-types', '~> 2.6'

gem 'rubyXL'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development do
  gem 'passenger'
end
