source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'rake'
wunderbar_version = File.read(File.expand_path("#{root}/wunderbar.version", __FILE__)).chomp
gem 'wunderbar', wunderbar_version
gem 'ruby2js', '3.2.0' # Travis fails with 3.3.[01]
gem 'sinatra', '~> 2.0'
gem 'nokogumbo'
gem 'execjs'
gem 'listen'
gem 'activesupport'
gem 'mail'
gem 'erubis'
gem 'mustache'

gem 'websocket-eventmachine-server'
gem 'websocket-client-simple'
gem 'concurrent-ruby'

gem 'rubyXL'

gem 'chronic'

group :test do
  gem 'rspec'
  gem 'puma'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development do
  gem 'passenger'
end
