source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'rake'
gem 'wunderbar', '>= 1.0.16'
gem 'ruby2js', '>= 2.0.13'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs', ('<2.5.1' if RUBY_VERSION =~ /^1/)
gem 'listen', ('~> 2.10' if RUBY_VERSION =~ /^1/)
gem 'activesupport'
gem 'mail'

gem 'mime-types', '~> 2.6'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
end

group :development do
  gem 'passenger'
end
