source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'mail'
gem 'rake'
gem 'wunderbar', '>= 1.2.6'
gem 'ruby2js'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs', ('<2.5.1' if RUBY_VERSION =~ /^1/)

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
end

group :demo do
  gem 'puma'
  gem 'listen', ('~> 3.0.7' if RUBY_VERSION =~ /^2\.[01]/)
end
