source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)

if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (at least for now)
  gem 'whimsy-asf'
end

gem 'mail'
gem 'rake'
gem 'wunderbar'
gem 'ruby2js'
gem 'sinatra'
gem 'nokogiri'
gem 'execjs'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
end

group :demo do
  gem 'puma'
  gem 'listen'
end
