source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
wunderbar_version = File.read(File.expand_path("#{root}/wunderbar.version", __FILE__)).chomp
ruby2js_version = File.read(File.expand_path("#{root}/ruby2js.version", __FILE__)).chomp

if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'mail'
gem 'rake'
gem 'wunderbar', wunderbar_version
gem 'ruby2js', ruby2js_version
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
end

group :demo do
  gem 'puma'
  gem 'listen'
end
