##   Licensed to the Apache Software Foundation (ASF) under one or more
##   contributor license agreements.  See the NOTICE file distributed with
##   this work for additional information regarding copyright ownership.
##   The ASF licenses this file to You under the Apache License, Version 2.0
##   (the "License"); you may not use this file except in compliance with
##   the License.  You may obtain a copy of the License at
## 
##       http://www.apache.org/licenses/LICENSE-2.0
## 
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

require 'whimsy/asf/config'

task :server => 'views/pages.js.rb' do
  ENV['RACK_ENV']='development'
  require 'wunderbar/listen'
end

file "views/pages.js.rb" => FileList['views/pages/*.js.rb'] do
  File.open('views/pages.js.rb', 'w') do |pages|
    # define a dummy superclass
    class React
    end

    # evaluate each page in a module, and output a 'require' statement for each
    Dir.chdir(File.expand_path('../views', __FILE__)) do
      Dir['pages/*.js.rb'].each do |page|
        eval "module Pages; #{File.read page}; end"
        pages.puts "require_relative #{page.sub(/\.js\.rb$/, '').inspect}"
      end
    end

    # output a list of page class names
    pages.print "\nPages = [\n  "
    pages.print Pages.constants.map(&:to_s).map(&:inspect).join(",\n  ")
    pages.puts "\n]"
  end
end
