source 'https://rubygems.org'

gem 'rake'
gem 'wunderbar', '>= 1.0.0'
gem 'ruby2js', '>= 2.0.0'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs', ('<2.5.1' if RUBY_VERSION =~ /^1/)
gem 'whimsy-asf', '>= 0.0.14'
gem 'listen', ('~> 2.10' if RUBY_VERSION =~ /^1/)

group :demo do
  gem 'puma'
end
