source 'https://rubygems.org'

root = '../..'
# lib needs these at run-time
gem 'json'
gem 'nokogiri'
gem 'rake'
gem 'ruby-ldap'
gem 'wunderbar'
gem 'pdf-reader'

# For Travis testing
group :test do
  gem 'whimsy-asf', path: File.expand_path('..', __dir__)
  gem 'rspec'
end
