source 'https://rubygems.org'

root = '../../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'mail'
gem 'rake'
gem 'zip'
gem 'sinatra', '~> 2.0'
gem 'sanitize'
gem 'wunderbar', '1.3.4'
gem 'ruby2js', '>= 2.1.18'
gem 'execjs'
gem 'listen'
gem 'escape'
gem 'pdf-reader'

group :demo do
  gem 'puma'
end
