##   Licensed to the Apache Software Foundation (ASF) under one or more
##   contributor license agreements.  See the NOTICE file distributed with
##   this work for additional information regarding copyright ownership.
##   The ASF licenses this file to You under the Apache License, Version 2.0
##   (the "License"); you may not use this file except in compliance with
##   the License.  You may obtain a copy of the License at
## 
##       http://www.apache.org/licenses/LICENSE-2.0
## 
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

require_relative 'config'

verbose false

task :default do
  puts 'Usage:'
  sh 'rake', '-T'
end

file 'Gemfile.lock' => 'Gemfile' do
  sh 'bundle update'
  touch 'Gemfile.lock'
end

desc 'install dependencies'
task :bundle => 'Gemfile.lock'

desc 'Parse emails'
task :parse => :bundle do
  ruby 'parsemail.rb'
end

desc 'Fetch and parse emails'
task :fetch => :bundle do
  ruby 'parsemail.rb', '--fetch'
end

desc 'create /srv/mail with the appropriate permissions'
file '/srv/mail' do
  begin
    mkdir_p '/srv/mail'

    require 'etc'
    if Etc.getpwent.uid == 0
      user = Etc.getpwnam(Etc.getlogin)
      chown user.uid, user.gid, '/srv/mail'
    end
  rescue Errno::EACCES
    sh 'sudo rake /srv/mail'
  end
end

desc 'download mail from whimsy-vm2'
task 'sync' => '/srv/mail' do
  sh 'rsync -av --delete whimsy-vm2.apache.org:/srv/mail/ /srv/mail'
end

desc 'Fetch and parse latest month only'
task :fetch1 => :bundle do
  ruby 'parsemail.rb', '--fetch1'
end

desc 'WebServer that provides an interface to explore emails'
task :server => :bundle do
  ENV['RACK_ENV']='development'

  require 'bundler/setup'
  require 'wunderbar'
  module Wunderbar::Listen
    EXCLUDE = [ARCHIVE]
  end

  require 'wunderbar/listen'
end

desc 'remove all parsed yaml files'
task :clean do
  rm_rf Dir["#{ARCHIVE}/*.yml"]
end
