source 'https://rubygems.org'

gem 'mail'
gem 'rake'
gem 'zip'
gem 'whimsy-asf'
gem 'sinatra'
gem 'sanitize'
gem 'wunderbar', '~> 1.0.11'
gem 'ruby2js', '~> 2.0.11'
gem 'execjs'

group :demo do
  gem 'listen'
  gem 'puma'
end
