source 'https://rubygems.org'

gem 'rake'
gem 'wunderbar', '>= 1.0.0'
gem 'ruby2js', '>= 2.0.0'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs'
gem 'mail'

group :development do
  gem 'passenger'
  gem 'listen'
end
