source 'https://rubygems.org'

root = '../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'rake'
gem 'wunderbar', '>= 1.0.0'
gem 'ruby2js', '>= 2.0.0'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs'

group :development do
  gem 'passenger'
  gem 'listen'
end
