source 'https://rubygems.org'

root = '../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
else
  # for docker purposes (atleast for now)
  gem 'whimsy-asf'
end

gem 'rake'
gem 'wunderbar', '>= 1.0.0'
gem 'ruby2js', '>= 2.0.0'
gem 'sinatra'
gem 'nokogumbo'
gem 'execjs', ('<2.5.1' if RUBY_VERSION =~ /^1/)
gem 'listen', ('~> 2.10' if RUBY_VERSION =~ /^1/)

group :demo do
  gem 'puma'
end
