require_relative 'models/attic'
require_relative 'models/auth'
require_relative 'models/committer'
require_relative 'models/committee'
require_relative 'models/nonpmc'
require_relative 'models/group'
require_relative 'models/ppmc'

require_relative 'models/ldap'
require_relative 'models/svn'
