source 'https://rubygems.org'

root = '../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
end

gem 'ruby2js', '>= 2.0.0'
gem 'regexp_parse' # Temp fix required by ruby2js 3.3.0, https://github.com/rubys/ruby2js/issues/54
wunderbar_version = File.read(File.expand_path("#{root}/wunderbar.version", __FILE__)).chomp
gem 'wunderbar', wunderbar_version
gem 'mail'
gem 'mime-types'

