source 'https://rubygems.org'

root = '../../..'
version_file = File.expand_path("#{root}/asf.version", __FILE__)
if File.exist? version_file
  # for deployment and local testing
  asf_version = File.read(version_file).chomp
  gem 'whimsy-asf', asf_version, path: File.expand_path(root, __FILE__)
end

gem 'ruby2js'
gem 'wunderbar'
gem 'mail'
gem 'mime-types'

